export const vietnameseQuotes: string[] = [
    "Có công mài sắt, có ngày nên kim.",
    "Đi một ngày đàng, học một sàng khôn.",
    "Ăn quả nhớ kẻ trồng cây.",
    "Uống nước nhớ nguồn.",
    "Thất bại là mẹ thành công.",
    "Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao.",
    "Gần mực thì đen, gần đèn thì sáng.",
    "Lá lành đùm lá rách.",
    "Bầu ơi thương lấy bí cùng, tuy rằng khác giống nhưng chung một giàn.",
    "Đói cho sạch, rách cho thơm.",
    "Giấy rách phải giữ lấy lề.",
    "Thương người như thể thương thân.",
    "Kiến tha lâu cũng đầy tổ.",
    "Tốt gỗ hơn tốt nước sơn.",
    "Cái nết đánh chết cái đẹp.",
    "Một miếng khi đói bằng một gói khi no.",
    "Có chí thì nên.",
    "Không thầy đố mày làm nên.",
    "Học thầy không tày học bạn.",
    "Muốn sang thì bắc cầu kiều, muốn con hay chữ thì yêu lấy thầy.",
    "Một chữ cũng là thầy, nửa chữ cũng là thầy.",
    "Lời nói chẳng mất tiền mua, lựa lời mà nói cho vừa lòng nhau.",
    "Im lặng là vàng.",
    "Ăn trông nồi, ngồi trông hướng.",
    "Học, học nữa, học mãi.",
    "Dốt đến đâu học lâu cũng biết.",
    "Thuận vợ thuận chồng, tát biển Đông cũng cạn.",
    "Đồng vợ đồng chồng, tát cạn biển Đông.",
    "Uốn cây từ thuở còn non, dạy con từ thuở hãy còn thơ ngây.",
    "Chim khôn kêu tiếng rảnh rang, người khôn nói tiếng dịu dàng dễ nghe.",
    "Chọn bạn mà chơi.",
    "Ở chọn nơi, chơi chọn bạn.",
    "Trăm hay không bằng tay quen.",
    "Có làm thì mới có ăn, không dưng ai dễ mang phần đến cho.",
    "Tay làm hàm nhai, tay quai miệng trễ.",
    "Máu chảy ruột mềm.",
    "Một giọt máu đào hơn ao nước lã.",
    "Chị ngã em nâng.",
    "Anh em như thể tay chân.",
    "Môi hở răng lạnh.",
    "Uống nước nhớ người đào giếng.",
    "Con hơn cha là nhà có phúc.",
    "Tôn sư trọng đạo.",
    "Nhất tự vi sư, bán tự vi sư.",
    "Kính thầy yêu bạn.",
    "Học đi đôi với hành.",
    "Đi hỏi già, về nhà hỏi trẻ.",
    "Chậm mà chắc.",
    "Nhanh nhẩu đoảng.",
    "Cần cù bù thông minh.",
    "Nước chảy đá mòn.",
    "Năng nhặt chặt bị.",
    "Đoàn kết là sức mạnh.",
    "Thắng không kiêu, bại không nản.",
    "Người ta là hoa đất.",
    "Một nụ cười bằng mười thang thuốc bổ.",
    "Sức khỏe là vàng.",
    "Có sức khỏe là có tất cả.",
    "Tri thức là sức mạnh.",
    "Sách là kho tàng tri thức của nhân loại.",
    "Đọc sách cho ta một cuộc đời.",
    "Thời gian là vàng bạc.",
    "Việc hôm nay chớ để ngày mai.",
    "Nói trước bước không qua.",
    "Nói chín thì phải làm mười, nói mười làm chín kẻ cười người chê.",
    "Tham thì thâm.",
    "Thật thà là cha quỷ quái.",
    "Cây ngay không sợ chết đứng.",
    "Gieo gió gặt bão.",
    "Ở hiền gặp lành.",
    "Ác giả ác báo.",
    "Chớ thấy sóng cả mà ngã tay chèo.",
    "Thua keo này ta bày keo khác.",
    "Sau cơn mưa trời lại sáng.",
    "Không có gì quý hơn độc lập tự do.",
    "Đất có lề, quê có thói.",
    "Phép vua thua lệ làng.",
    "Đi với bụt mặc áo cà sa, đi với ma mặc áo giấy.",
    "Nhập gia tùy tục.",
    "Cẩn tắc vô áy náy.",
    "Mất bò mới lo làm chuồng.",
    "Sai một ly, đi một dặm.",
    "Ngựa quen đường cũ.",
    "Đánh trống bỏ dùi.",
    "Đầu voi đuôi chuột.",
    "Rừng vàng biển bạc.",
    "Tấc đất tấc vàng.",
    "Người sống đống vàng.",
    "Đoàn kết, đoàn kết, đại đoàn kết. Thành công, thành công, đại thành công.",
    "Dĩ bất biến, ứng vạn biến.",
    "Không có việc gì khó, chỉ sợ lòng không bền.",
    "Đào núi và lấp biển, quyết chí ắt làm nên.",
    "Công cha như núi Thái Sơn, nghĩa mẹ như nước trong nguồn chảy ra.",
    "Mẹ tròn con vuông.",
    "Con có cha như nhà có nóc.",
    "Cha nào con nấy.",
    "Rau nào sâu nấy.",
    "Giỏ nhà ai, quai nhà nấy.",
    "Con dại cái mang.",
    "Yêu cho roi cho vọt, ghét cho ngọt cho bùi.",
    "Thương cho roi cho vọt.",
    "Thuốc đắng dã tật, sự thật mất lòng.",
    "Của cho không bằng cách cho.",
    "Được voi đòi tiên.",
    "Đứng núi này trông núi nọ.",
    "No dồn đói góp.",
    "Lửa thử vàng, gian nan thử sức.",
    "Vạn sự khởi đầu nan.",
    "Đầu xuôi đuôi lọt.",
    "Cờ đến tay ai người ấy phất.",
    "Ăn cỗ đi trước, lội nước theo sau.",
    "Dễ như trở bàn tay.",
    "Khỏe như vâm.",
    "Nhanh như chớp.",
    "Chậm như sên.",
    "Gan vàng dạ sắt.",
    "Chân cứng đá mềm.",
    "Mạnh vì gạo, bạo vì tiền.",
    "Có tiền mua tiên cũng được.",
    "Tiền nào của nấy.",
    "Của rẻ là của ôi.",
    "Mua danh ba vạn, bán danh ba đồng.",
    "Tốt danh hơn tốt áo.",
    "Chết vinh còn hơn sống nhục.",
    "Chết trong còn hơn sống đục.",
    "Một người vì mọi người, mọi người vì một người.",
    "Dân giàu, nước mạnh.",
    "An cư lạc nghiệp.",
    "Buôn có bạn, bán có phường.",
    "Khách hàng là thượng đế.",
    "Vui lòng khách đến, vừa lòng khách đi.",
    "Biết người biết ta, trăm trận trăm thắng.",
    "Lùi một bước, tiến ba bước.",
    "Dục tốc bất đạt.",
    "Oán thù nên cởi không nên buộc.",
    "Thêm bạn bớt thù.",
    "Bán anh em xa, mua láng giềng gần.",
    "Tối lửa tắt đèn có nhau.",
    "Một điều nhịn, chín điều lành.",
    "Ăn được ngủ được là tiên.",
    "Giận quá mất khôn.",
    "Cả giận mất khôn.",
    "Trông mặt mà bắt hình dong.",
    "Đừng trông mặt mà bắt hình dong.",
    "Nước trong quá thì không có cá, người xét nét quá thì không có bạn.",
    "Sông có khúc, người có lúc.",
    "Mỗi hoa mỗi hương, mỗi người mỗi nết.",
    "Không ai hoàn hảo cả.",
    "Nhân vô thập toàn.",
    "Đời cha ăn mặn, đời con khát nước.",
    "Con nhà tông, không giống lông cũng giống cánh.",
    "Tre già măng mọc.",
    "Thế hệ sau hơn thế hệ trước.",
    "Trường giang sóng sau xô sóng trước.",
    "Cười người hôm trước, hôm sau người cười.",
    "Tránh vỏ dưa gặp vỏ dừa.",
    "Khôn ngoan đối đáp người ngoài, gà cùng một mẹ chớ hoài đá nhau.",
    "Mất của tìm người, mất người tìm đâu.",
    "Của đi thay người.",
    "Người đẹp vì lụa.",
    "Lúa tốt vì phân.",
    "Nước đổ lá khoai.",
    "Nước đổ đầu vịt.",
    "Đàn gảy tai trâu.",
    "Thùng rỗng kêu to.",
    "Ếch ngồi đáy giếng.",
    "Xem người xem tận tâm trong, xem cây xem tận gốc rễ ngọn ngành.",
    "Miệng nam mô, bụng một bồ dao găm.",
    "Khẩu phật tâm xà.",
    "Bụt trên tòa, gà nào dám mổ.",
    "Ăn chay niệm phật.",
    "Xa mặt cách lòng.",
    "Yêu nhau mấy núi cũng trèo, mấy sông cũng lội, mấy đèo cũng qua.",
    "Đường đi hay tối, nói dối hay cùng.",
    "Sự thật thì đắng, nhưng kết quả thì ngọt ngào.",
    "Một lần bất tín, vạn lần bất tin.",
    "Qua cầu rút ván.",
    "Ăn cháo đá bát.",
    "Vắt chanh bỏ vỏ.",
    "Được chim bỏ ná, được cá quên nơm.",
    "Có mới nới cũ.",
    "Thấy sang bắt quàng làm họ.",
    "Cháy nhà ra mặt chuột.",
    "Hoạn nạn mới biết bạn hiền.",
    "Chơi với chó, chó liếm mặt.",
    "Nuôi ong tay áo.",
    "Nuôi cáo trong nhà.",
    "Rước voi về giày mả tổ.",
    "Cõng rắn cắn gà nhà.",
    "Dao sắc không gọt được chuôi.",
    "Bụt chùa nhà không thiêng.",
    "Sảy cha còn chú, sảy mẹ bú dì.",
    "Mẹ ghẻ con chồng.",
    "Chín người mười ý."
];
